In [132]:
import numpy as np

# 1 D array


## Array creation

### array()


In [133]:
a=np.array([2,4,6,8])
print(a)

[2 4 6 8]


### arange()

In [134]:
a=np.arange(2,10,2)
print(a)


[2 4 6 8]


### zeros()

In [135]:
a=np.zeros(3,) #Default dtype=float to remove this do dtype=int
print(a)

[0. 0. 0.]


In [136]:
a=np.zeros(3,dtype=int)
print(a)

[0 0 0]


### ones()

In [137]:
a=np.ones(3) #Default dtype=float to remove this do dtype=int
print(a)

[1. 1. 1.]


In [138]:
a=np.ones(3,dtype=int)
print(a)

[1 1 1]


### full()

It gives an array of required shape with a given fixed fill value 
Like if (3,5) is given it means 3 elements with 5 value

In [139]:
a=np.full(3, 5.0) #Data type is of the filled value 
print(a)

[5. 5. 5.]


### Linspace()

It gives an array of evenly spaced values over a specified interval 
Like in below example 5 equal spaced value between 1 and 10 is given 

In [140]:
a=np.linspace(1, 10, 5) #Start, Stop, Number of points
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


### Logspace()

Generated an array with a given number of points in a given interval but in log space 

In [141]:
a=np.logspace(1, 10, 5) #Start, Stop, Number of points
print(a)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


### Identity()

Gives an identity matrix of given shape

In [142]:
a=np.identity(3,dtype=int) #Identity matrix of size 3x3
print(a) # Default dtype=float to remove this do dtype=int

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Eye()

This also gives an identity matrix but here we are able to move the diagonal 1 up and down with the help of a parameter 
And it can also give non square identity matrix see code third

In [143]:
a=np.eye(3)
print(a) #Identity matrix of size 3x3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [144]:
a=np.eye(3, k=1) #Identity matrix of size 3x3 with diagonal offset by 1
print(a) # Default dtype=float to remove this do dtype=int

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [145]:
a=np.eye(3,2,k=1) #Identity matrix of size 3x2 with diagonal offset by 1
print(a) # Default dtype=float to remove this do dtype=int

[[0. 1.]
 [0. 0.]
 [0. 0.]]


### _like family Function

They act as a cloning tool and is used to copy the shape and datatype of an existing array 

#### zeros_like()

In [146]:
b=np.zeros_like(a) #Returns an array of zeros with the same shape and type as a
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


#### ones_like()

In [147]:
b=np.ones_like(a) #Returns an array of ones with the same shape and type as a
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### full_like()

In [148]:
b=np.full_like(a, 5.0) #Returns an array of filled values with the same shape and type as a
print(b)

[[5. 5.]
 [5. 5.]
 [5. 5.]]


### Random Array Creation

#### random.rand()

In [149]:
a=np.random.rand(3,3) #Random numbers from uniform distribution over [0, 1)
print(a)

[[0.77542932 0.61707472 0.53903134]
 [0.16953434 0.31727111 0.97756393]
 [0.83436414 0.75155208 0.02018933]]


#### random.randn()

In [150]:
a=np.random.randn(3,3) #Random numbers from standard normal distribution
print(a)

[[ 1.96804012 -1.4215628  -0.13117508]
 [-0.2816885   1.25186423  0.23069586]
 [ 1.07434585  1.95001552 -0.72959555]]


#### random.randint()

In [151]:
a=np.random.randint(1, 10,size=3) 
print(a)

[6 4 4]


#

# 2D array

### Attributes of 2D array

In [152]:
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


#### shape

It returns the shape of the array in tuple form

In [153]:
a.shape #Returns the shape of the array
#

(2, 3)

#### size

In [154]:
a.size #Returns the number of elements in the array

6

#### dtype

In [155]:
a.dtype #Returns the data type of the array

dtype('int64')

#### itemsize

In [156]:
a.itemsize #Returns the size in bytes of each element in the array

8

#### nbytes

In [157]:
a.nbytes #Returns the total size in bytes of the array

48

## Creation of 2d array

### array()

In [159]:
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


### rest all the function will act same only the shape parameter will get added there 
Like in ones 
np.ones((3,4))
It will a 2D array of 3 rows and 4 columns and every elemnts be 1 

In [160]:
a=np.ones((3,4),dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


### 

### 