In [3]:
import numpy as np

# ----> Accessing Array 

### Simple index

In [4]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Accesing single element

-------> similar to list

In [22]:
a[0]

array([1, 2, 3])

In [24]:
a[0][0]

np.int64(1)

### Accesing multiple element 

------> Here there is a trick like hum list ki tarah hi kr skte hai oor iss mai [] iske andr hum comma krke bhi likh skte hai . Ot ye act karega jaise a[0][1]

In [28]:
a[0][1]

np.int64(2)

In [27]:
a[0,1]

np.int64(2)

In [ ]:
a[[0,1]] # Yahan ye 0 and 1 row ko access karega

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a[,[0,1]] # ye nhi chalega kyuki hum sidha column ko access kar rahe hai without row index

SyntaxError: invalid syntax (4164635079.py, line 1)

---------> yahan bhi hum slicing use kr skte hai same as List

In [32]:
a[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0:2, 0:2] #will work on corresponding row and column . 

array([[1, 2],
       [4, 5]])

-------> Yahan agr hum a[[0,1],[0,1]] tho ye corresponding elements uthaega 

In [20]:
a[[0,1], [0,1]] #will work on corresponding row and column

array([1, 5])

In [25]:
a[0:2,[0,1]] # it means 0 ke liye 0,1 column chalega then 1 ke liye 0,1 chalega 

array([[1, 2],
       [4, 5]])

In [26]:
a[1:3,[1,2]]

array([[5, 6],
       [8, 9]])

In [ ]:
a[::-1] # ye reverse kar dega array ko

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
a[::-1,::-1] # ye reverse kar dega array ko row and column dono ke liye

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

#### Transpose 

In [39]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])