In [1]:
import numpy as np

In [3]:
a=np.random.randint(1,100,size=(2,3))
print(a)

[[90  7 45]
 [83 47 59]]


In [4]:
b=np.random.randint(1,100,size=(2,3))
print(b)

[[52 25 10]
 [92 83 23]]


## Their are two types of stacks in array

### Horizontal stack ----------> hstack
* NO. ROWS MUST BE SAME
* IT CONTAINS DTYPE PARAMETER

In [8]:
np.hstack((a,b))

array([[90,  7, 45, 52, 25, 10],
       [83, 47, 59, 92, 83, 23]], dtype=int32)

In [9]:
np.hstack((a,b),dtype=np.float64)

array([[90.,  7., 45., 52., 25., 10.],
       [83., 47., 59., 92., 83., 23.]])

### Vertical stack --------------> vstack
* NO. OF COLUMNS MUST BE SAME

In [6]:
np.vstack((a,b))

array([[90,  7, 45],
       [83, 47, 59],
       [52, 25, 10],
       [92, 83, 23]], dtype=int32)

In [10]:
np.vstack((a,b),dtype=np.float64)

array([[90.,  7., 45.],
       [83., 47., 59.],
       [52., 25., 10.],
       [92., 83., 23.]])

### Stack Operator
* It can do both hstack and vstack depending on the axis we give 
* For vstack Axis=0 , hstack Axis=1 
* Process is little Bit different 

#### IN VSTACK OPERATION IT PRINTS AN ARRAY AFTER OTHER

In [11]:
np.stack((a,b),axis=0)

array([[[90,  7, 45],
        [83, 47, 59]],

       [[52, 25, 10],
        [92, 83, 23]]], dtype=int32)

##### IN HSTACK OPERATION HERE IT TAKES INDEX ROW 0 OF A WITH ROW 0 OF B MAKES IT A SUBARAY AND SAME WITH ALL THE ROWS 
* IT IS LITTLE BIT DIFFERENT THAN HSTACK OPERATION 

In [12]:
np.stack((a,b),axis=1)

array([[[90,  7, 45],
        [52, 25, 10]],

       [[83, 47, 59],
        [92, 83, 23]]], dtype=int32)