In [1]:
import numpy as np

In [3]:
a=np.random.randint(1,100,size=12)
a

array([56, 52, 72, 79, 51, 64, 17, 42, 23, 20, 25, 31], dtype=int32)

In [4]:
a.ndim

1

## RESHAPE
* CONVERTS 1D INTO 2D AND VICE VERSA

In [5]:
# 2D------> rows and columns
#12-------> 3 rows and 4 columns
#12--------> 4 rows and 3 columns
#AND SO ON 
np.reshape(a,(3,4)) # IT WILL RESHAPE THE ARRAY INTO 3 ROWS AND 4 COLUMNS

array([[56, 52, 72, 79],
       [51, 64, 17, 42],
       [23, 20, 25, 31]], dtype=int32)

In [7]:
b=np.random.randint(1,100,size=(2,5))
b

array([[29, 27, 80, 95, 24],
       [55, 76, 16, 58, 14]], dtype=int32)

In [8]:
np.reshape(b,10) # IT WILL RESHAPE THE ARRAY INTO 1D ARRAY WITH 10 ELEMENTS

array([29, 27, 80, 95, 24, 55, 76, 16, 58, 14], dtype=int32)

### CREATE A PROGRAM TO PRINT FIRST 10 EVEN NUMBERS IN 5,2 SHAPE

In [10]:
a=np.arange(2,21,2).reshape(5,2)
a

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])