In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,100,size=(2,3))
print(a)    

[[71 77 61]
 [60 82 45]]


## Tile 
* IF WE WANT TO REPEAT PURRA ARRAY THEN USE TILE 

In [ ]:
np.tile(a,4) # IT WILL REPEAT THE ARRAY 4 TIMES IN HORIZONTAL DIRECTION

array([[71, 77, 61, 71, 77, 61, 71, 77, 61, 71, 77, 61],
       [60, 82, 45, 60, 82, 45, 60, 82, 45, 60, 82, 45]], dtype=int32)

In [4]:
np.tile(a,(2,4)) # IT WILL REPEAT THE ARRAY 2 TIMES IN VERTICAL DIRECTION AND 4 TIMES IN HORIZONTAL DIRECTION

array([[71, 77, 61, 71, 77, 61, 71, 77, 61, 71, 77, 61],
       [60, 82, 45, 60, 82, 45, 60, 82, 45, 60, 82, 45],
       [71, 77, 61, 71, 77, 61, 71, 77, 61, 71, 77, 61],
       [60, 82, 45, 60, 82, 45, 60, 82, 45, 60, 82, 45]], dtype=int32)

## Repeat
* IF WE WANT TO REPEAT AN ELEMENT N NO. OF TIMES THEN USE REPEAT

In [6]:
np.repeat(a,4) # IT WILL REPEAT THE ELEMENTS OF ARRAY 4 TIMES IN HORIZONTAL DIRECTION

array([71, 71, 71, 71, 77, 77, 77, 77, 61, 61, 61, 61, 60, 60, 60, 60, 82,
       82, 82, 82, 45, 45, 45, 45], dtype=int32)

In [ ]:
np.repeat(a,3,axis=1) # IT WILL REPEAT THE ELEMENTS OF ARRAY 3 TIMES IN HORIZONTAL DIRECTION

array([[71, 71, 71, 77, 77, 77, 61, 61, 61],
       [60, 60, 60, 82, 82, 82, 45, 45, 45]], dtype=int32)

In [11]:
np.repeat(a,3,axis=0) # IT WILL REPEAT THE ELEMENTS OF ARRAY 3 TIMES IN VERTICAL DIRECTION

array([[71, 77, 61],
       [71, 77, 61],
       [71, 77, 61],
       [60, 82, 45],
       [60, 82, 45],
       [60, 82, 45]], dtype=int32)