In [5]:
import numpy as np

In [6]:
marks=np.random.randint(1,100,size=5)
marks

array([87, 11, 47, 92, 66], dtype=int32)

## WHERE ()
* IT IS USED TO ENCODE DATA AND USEED TO TRANSFORM DATA 
* IF WE HAVE TO PERFORM ONLY TWO OPERATION(IF AND ELSE VALA HISAB KITAB)

In [4]:
np.where(marks>50) # IT WILL RETURN THE INDEX OF THE ELEMENTS WHICH ARE GREATER THAN 50

(array([3, 4]),)

In [9]:
marks[np.where(marks>50)] # IT WILL RETURN THE ELEMENTS WHICH ARE GREATER THAN 50 AS "Pass" AND LESS THAN 50 AS "Fail"

array([87, 92, 66], dtype=int32)

## SELECT
* IT IS USED WHEN WE WANT TO ASSIGN DATA BY CONSIDERING VARIOUS CONDITIONS
* IF ELIF ELSE VALA HISAB KITAB

In [6]:
np.select([marks>=90,marks>=80,marks>=70,marks>=60,marks>=50],[ "A+","A","B","C","D"],default="F") # IT WILL RETURN THE GRADE OF THE STUDENT BASED ON THE MARKS OBTAINED

array(['F', 'F', 'F', 'B', 'B'], dtype='<U2')